# Generated by Django 6.0.5 on 2026-06-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_apaar_second_mobile_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='apaar_id',
            field=models.CharField(blank=True, help_text='Academic Bank of Credits ID — see apaar.education.gov.in', max_length=20, verbose_name='APAAR ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_mobile',
            field=models.CharField(blank=True, help_text='Secondary contact number (parent/guardian)', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='sport',
            field=models.CharField(blank=True, help_text='Sport activity / event the student participates in', max_length=100),
        ),
    ]
