# Generated by Django 6.0.4 on 2026-06-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_apaar_id_alter_student_second_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fourth_mobile',
            field=models.CharField(blank=True, help_text='Fourth contact number', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='third_mobile',
            field=models.CharField(blank=True, help_text='Third contact number', max_length=15),
        ),
    ]
