# Generated by Django 6.0.4 on 2026-06-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_add_third_fourth_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marks_biology',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Biology'),
        ),
        migrations.AddField(
            model_name='student',
            name='marks_english',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='English'),
        ),
        migrations.AddField(
            model_name='student',
            name='marks_hindi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hindi'),
        ),
        migrations.AddField(
            model_name='student',
            name='marks_maths',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Maths'),
        ),
        migrations.AddField(
            model_name='student',
            name='marks_physics',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Physics'),
        ),
        migrations.AddField(
            model_name='student',
            name='marks_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Social'),
        ),
        migrations.AddField(
            model_name='student',
            name='marks_telugu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Telugu'),
        ),
        migrations.AddField(
            model_name='student',
            name='marks_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total Marks'),
        ),
        migrations.AddField(
            model_name='student',
            name='prev_school_location',
            field=models.CharField(blank=True, max_length=150, verbose_name='School Location'),
        ),
        migrations.AddField(
            model_name='student',
            name='prev_school_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Previous School Name'),
        ),
    ]
