# Generated by Django 5.2.15 on 2026-07-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_superuser_nouman'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='assigned_sections',
            field=models.ManyToManyField(blank=True, help_text='Sections this faculty can access for attendance', related_name='faculty_members', to='accounts.section'),
        ),
    ]
