# Generated by Django 5.2.15 on 2026-08-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_assigned_sections'),
        ('marks', '0007_alter_examcategory_options_alter_examtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='assigned_subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects this faculty can enter marks for', related_name='faculty_members', to='marks.subject'),
        ),
    ]
