# Generated by Django 5.2.15 on 2026-09-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feepayment_student_fee_feetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
