# Generated by Django 5.2.15 on 2026-07-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bg_color',
            field=models.CharField(default='#f3f4f6', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='border_color',
            field=models.CharField(default='#9ca3af', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(default='#374151', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.CharField(default='bi-grid-fill', max_length=50),
        ),
        migrations.AddField(
            model_name='group',
            name='subjects_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
