# Generated by Django 5.2.15 on 2026-07-10 15:05

from django.db import migrations
from django.contrib.auth.hashers import make_password

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_bg_color_group_border_color_group_color_and_more'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, reverse_code=migrations.RunPython.noop),
    ]

