# Generated by Django 5.2.15 on 2026-07-10 15:05

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    if not User.objects.filter(username='nouman').exists():
        User.objects.create(
            username='nouman',
            email='nouman@example.com',
            password=make_password('nouman@123'),
            is_superuser=True,
            is_staff=True,
            is_active=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_bg_color_group_border_color_group_color_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
