# Generated by Django 5.2.15 on 2026-07-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginsession_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='login_role',
            field=models.CharField(blank=True, default='', help_text='User role at login time — used for session expiry limits', max_length=20),
        ),
    ]
