# Generated by Django 5.2.15 on 2026-07-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_loginsession_login_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_reason',
            field=models.TextField(blank=True, help_text='Reason for blocking (shown to user on login)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked_by_admin',
            field=models.BooleanField(default=False, help_text='Manually blocked by admin'),
        ),
    ]
