# Generated by Django 5.2.15 on 2026-09-23 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seed_core_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.academicyear'),
        ),
        migrations.AlterField(
            model_name='section',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.academicyear'),
        ),
        migrations.AlterField(
            model_name='section',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='accounts.group'),
        ),
    ]
