# Generated by Django 6.0.4 on 2026-06-21 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_add_school_info_and_subject_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipe_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='IPE Marks')),
                ('jee_main_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='JEE Main Marks')),
                ('jee_main_password', models.CharField(blank=True, max_length=100, verbose_name='JEE Main Password')),
                ('eamcet_hall_ticket', models.CharField(blank=True, max_length=30, verbose_name='EAMCET Hall Ticket')),
                ('eamcet_password', models.CharField(blank=True, max_length=100, verbose_name='EAMCET Password')),
                ('eamcet_result', models.CharField(blank=True, max_length=100, verbose_name='EAMCET Result / Rank')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_info', to='students.student')),
            ],
        ),
    ]
