# Generated by Django 6.0.4 on 2026-06-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexaminfo',
            name='eamcet_result',
        ),
        migrations.RemoveField(
            model_name='studentexaminfo',
            name='ipe_marks',
        ),
        migrations.RemoveField(
            model_name='studentexaminfo',
            name='jee_main_marks',
        ),
        migrations.RemoveField(
            model_name='studentexaminfo',
            name='jee_main_password',
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='eamcet_date_of_exam',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='eamcet_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='eamcet_rank',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='ipe_1st_english',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='ipe_1st_s3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='ipe_1st_s4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='ipe_1st_s5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='ipe_1st_s6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='ipe_1st_telugu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='ipe_1st_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='ipe_2nd_english',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='ipe_2nd_s3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='ipe_2nd_s4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='ipe_2nd_s5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='ipe_2nd_s6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='ipe_2nd_telugu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='ipe_2nd_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='ipe_hall_ticket',
            field=models.CharField(blank=True, max_length=30, verbose_name='IPE Hall Ticket'),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='jee_date_of_exam',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='jee_hall_ticket',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentexaminfo',
            name='jee_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentexaminfo',
            name='eamcet_hall_ticket',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='studentexaminfo',
            name='eamcet_password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
