# Generated by Django 5.2.15 on 2026-09-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_expand_exam_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexaminfo',
            name='eamcet_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentexaminfo',
            name='jee_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
