# Generated by Django 5.2.15 on 2026-08-08 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_assigned_sections'),
        ('students', '0008_alter_student_academic_year_alter_student_section'),
        ('whatsapp', '0002_whatsappsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingmessage',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='pendingmessage',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='students.student'),
        ),
    ]
