# Generated by Django 5.2.17 on 2026-08-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_pendingmessage_faculty_alter_pendingmessage_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingmessage',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='pendingmessage',
            name='message_type',
            field=models.CharField(choices=[('template', 'Template'), ('text', 'Text')], default='template', max_length=10),
        ),
        migrations.AddField(
            model_name='pendingmessage',
            name='template_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pendingmessage',
            name='template_params',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
