# Generated by Django 5.2.15 on 2026-08-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_pendingmessage_language_pendingmessage_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingmessage',
            name='wamid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pendingmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
