# Generated by Django 5.2.15 on 2026-09-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_pendingmessage_wamid_alter_pendingmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingmessage',
            name='attendance_date',
            field=models.DateField(blank=True, help_text='Date of attendance associated with this message', null=True),
        ),
    ]
