# Generated by Django 5.2.15 on 2026-09-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_pendingmessage_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
