# Generated by Django 5.2.15 on 2026-10-02 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_group_academic_year_and_more'),
        ('faculty', '0003_faculty_assigned_subjects'),
        ('students', '0010_alter_student_academic_year_alter_student_section'),
        ('whatsapp', '0007_alter_pendingmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingmessage',
            name='category',
            field=models.CharField(choices=[('MARKS', 'Marks'), ('ATTENDANCE', 'Attendance'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=12),
        ),
        migrations.AddField(
            model_name='pendingmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingmessage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.group'),
        ),
        migrations.AddField(
            model_name='pendingmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingmessage',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.section'),
        ),
        migrations.AddField(
            model_name='pendingmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='pendingmessage',
            index=models.Index(fields=['category', 'created_at'], name='whatsapp_pe_categor_025863_idx'),
        ),
    ]
