# Generated by Django 6.0.6 on 2026-06-14 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.CharField(choices=[('ipe', 'IPE'), ('eamcet_jee', 'EAMCET / JEE Main'), ('eamcet', 'EAMCET'), ('neet', 'NEET')], default='ipe', help_text='Decides which subjects appear on the marks entry screen.', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Student group (MPIC / BPIC / CEC / MEC) this exam is for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='accounts.group'),
        ),
    ]
