# Generated by Django 6.0.6 on 2026-06-14 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_exam_category_exam_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(choices=[('ipe', 'IPE'), ('jee', 'JEE Main'), ('eamcet', 'EAMCET'), ('neet', 'NEET')], default='ipe', help_text='Decides which subjects appear on the marks entry screen.', max_length=20),
        ),
        migrations.CreateModel(
            name='ExamSubjectMaxMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('max_marks', models.IntegerField(default=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_max_marks', to='marks.exam')),
            ],
            options={
                'unique_together': {('exam', 'subject')},
            },
        ),
    ]
