# Generated by Django 6.0.4 on 2026-06-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_alter_exam_category_examsubjectmaxmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(choices=[('ipe', 'IPE'), ('jee', 'JEE Main'), ('eamcet', 'EAPCET'), ('neet', 'NEET'), ('cuet', 'CUET')], default='ipe', help_text='Decides which subjects appear on the marks entry screen.', max_length=20),
        ),
    ]
