# Generated by Django 5.2.15 on 2026-07-07 12:43
# Rewritten: the original AlterField operations tried to convert Exam.category,
# Exam.exam_type, ExamSubjectMaxMark.subject and Mark.subject directly from
# CharField to ForeignKey. That silently "worked" against an empty/local dev
# database, but fails against any database that already has real rows (e.g.
# category='ipe', exam_type='unit1', subject='Maths') because Postgres can't
# cast those existing strings into the new bigint FK columns. This version
# preserves existing data: it renames each old string column out of the way,
# adds the new FK column, backfills it by creating matching lookup rows
# (ExamCategory/ExamType/Subject) from the legacy string values, then drops
# the old column.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('marks', '0004_alter_exam_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bg_color', models.CharField(default='#f3f4f6', max_length=20)),
                ('text_color', models.CharField(default='#374151', max_length=20)),
                ('icon', models.CharField(default='bi-book', max_length=50)),
                ('is_fixed_marks', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Exam Categories',
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),

        # Drop unique_together constraints that reference fields we're about to rename,
        # so the intermediate migration states stay valid.
        migrations.AlterUniqueTogether(name='examsubjectmaxmark', unique_together=set()),
        migrations.AlterUniqueTogether(name='mark', unique_together=set()),

        # --- Exam.category: CharField -> ForeignKey(ExamCategory), preserving data ---
        migrations.RenameField(model_name='exam', old_name='category', new_name='category_old'),
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.examcategory', help_text='Decides which subjects appear on the marks entry screen.'),
        ),

        # --- Exam.exam_type: CharField -> ForeignKey(ExamType), preserving data ---
        migrations.RenameField(model_name='exam', old_name='exam_type', new_name='exam_type_old'),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.examtype'),
        ),

        # --- ExamSubjectMaxMark.subject: CharField -> ForeignKey(Subject), preserving data ---
        migrations.RenameField(model_name='examsubjectmaxmark', old_name='subject', new_name='subject_old'),
        migrations.AddField(
            model_name='examsubjectmaxmark',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.subject'),
        ),

        # --- Mark.subject: CharField -> ForeignKey(Subject), preserving data ---
        migrations.RenameField(model_name='mark', old_name='subject', new_name='subject_old'),
        migrations.AddField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.subject'),
        ),
        # NOTE: the data backfill (RunPython) and the "drop old columns / tighten to
        # non-null" steps both live in LATER migrations (0005b, 0005a) on purpose.
        # AddField above queues deferred index-creation SQL that Postgres only
        # flushes at the end of *this* migration's transaction — if a RunPython data
        # UPDATE happened earlier in that same transaction, the flush fails with
        # "cannot CREATE INDEX ... because it has pending trigger events". Keeping
        # this migration to schema-only changes (no data UPDATEs) avoids that.
    ]
