# Generated by Django 5.2.15 on 2026-07-07 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('marks', '0004_alter_exam_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bg_color', models.CharField(default='#f3f4f6', max_length=20)),
                ('text_color', models.CharField(default='#374151', max_length=20)),
                ('icon', models.CharField(default='bi-book', max_length=50)),
                ('is_fixed_marks', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Exam Categories',
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(help_text='Decides which subjects appear on the marks entry screen.', on_delete=django.db.models.deletion.CASCADE, to='marks.examcategory'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.examtype'),
        ),
        migrations.AlterField(
            model_name='examsubjectmaxmark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.subject'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.subject'),
        ),
        migrations.CreateModel(
            name='GroupCategoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.examcategory')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
                ('subjects', models.ManyToManyField(to='marks.subject')),
            ],
            options={
                'unique_together': {('group', 'category')},
            },
        ),
    ]
