# Generated by Django 5.2.15 on 2026-07-07 12:43
# Rewritten: the original AlterField operations tried to convert Exam.category,
# Exam.exam_type, ExamSubjectMaxMark.subject and Mark.subject directly from
# CharField to ForeignKey. That silently "worked" against an empty/local dev
# database, but fails against any database that already has real rows (e.g.
# category='ipe', exam_type='unit1', subject='Maths') because Postgres can't
# cast those existing strings into the new bigint FK columns. This version
# preserves existing data: it renames each old string column out of the way,
# adds the new FK column, backfills it by creating matching lookup rows
# (ExamCategory/ExamType/Subject) from the legacy string values, then drops
# the old column.

import django.db.models.deletion
from django.db import migrations, models


CATEGORY_LABELS = {
    'ipe': 'IPE',
    'jee': 'JEE Main',
    'eamcet': 'EAPCET',
    'eamcet_jee': 'EAMCET / JEE Main',
    'neet': 'NEET',
    'cuet': 'CUET',
}

EXAM_TYPE_LABELS = {
    'unit1': 'Unit Test 1',
    'unit2': 'Unit Test 2',
    'quarterly': 'Quarterly Exam',
    'halfyearly': 'Half-Yearly Exam',
    'prefinal': 'Pre-Final Exam',
    'final': 'Final Exam',
    'custom': 'Custom Exam',
}


def backfill_fk_data(apps, schema_editor):
    Exam = apps.get_model('marks', 'Exam')
    ExamSubjectMaxMark = apps.get_model('marks', 'ExamSubjectMaxMark')
    Mark = apps.get_model('marks', 'Mark')
    ExamCategory = apps.get_model('marks', 'ExamCategory')
    ExamType = apps.get_model('marks', 'ExamType')
    Subject = apps.get_model('marks', 'Subject')

    # --- Exam.category: legacy string -> ExamCategory row ---
    cat_ids = {}
    for val in Exam.objects.values_list('category_old', flat=True).distinct():
        key = val or 'ipe'
        if key not in cat_ids:
            label = CATEGORY_LABELS.get(key, key.upper())
            cat, _ = ExamCategory.objects.get_or_create(name=label)
            cat_ids[key] = cat.id
        Exam.objects.filter(category_old=val).update(category_id=cat_ids[key])

    # --- Exam.exam_type: legacy string -> ExamType row ---
    type_ids = {}
    for val in Exam.objects.values_list('exam_type_old', flat=True).distinct():
        key = val or 'custom'
        if key not in type_ids:
            label = EXAM_TYPE_LABELS.get(key, key.title())
            et, _ = ExamType.objects.get_or_create(name=label)
            type_ids[key] = et.id
        Exam.objects.filter(exam_type_old=val).update(exam_type_id=type_ids[key])

    # --- Subject: shared lookup for both ExamSubjectMaxMark.subject and Mark.subject ---
    subj_ids = {}

    def subject_id_for(raw_name):
        name = (raw_name or '').strip() or 'Unknown'
        if name not in subj_ids:
            s, _ = Subject.objects.get_or_create(name=name)
            subj_ids[name] = s.id
        return subj_ids[name]

    for val in ExamSubjectMaxMark.objects.values_list('subject_old', flat=True).distinct():
        ExamSubjectMaxMark.objects.filter(subject_old=val).update(subject_id=subject_id_for(val))

    for val in Mark.objects.values_list('subject_old', flat=True).distinct():
        Mark.objects.filter(subject_old=val).update(subject_id=subject_id_for(val))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('marks', '0004_alter_exam_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bg_color', models.CharField(default='#f3f4f6', max_length=20)),
                ('text_color', models.CharField(default='#374151', max_length=20)),
                ('icon', models.CharField(default='bi-book', max_length=50)),
                ('is_fixed_marks', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Exam Categories',
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),

        # Drop unique_together constraints that reference fields we're about to rename,
        # so the intermediate migration states stay valid.
        migrations.AlterUniqueTogether(name='examsubjectmaxmark', unique_together=set()),
        migrations.AlterUniqueTogether(name='mark', unique_together=set()),

        # --- Exam.category: CharField -> ForeignKey(ExamCategory), preserving data ---
        migrations.RenameField(model_name='exam', old_name='category', new_name='category_old'),
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.examcategory', help_text='Decides which subjects appear on the marks entry screen.'),
        ),

        # --- Exam.exam_type: CharField -> ForeignKey(ExamType), preserving data ---
        migrations.RenameField(model_name='exam', old_name='exam_type', new_name='exam_type_old'),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.examtype'),
        ),

        # --- ExamSubjectMaxMark.subject: CharField -> ForeignKey(Subject), preserving data ---
        migrations.RenameField(model_name='examsubjectmaxmark', old_name='subject', new_name='subject_old'),
        migrations.AddField(
            model_name='examsubjectmaxmark',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.subject'),
        ),

        # --- Mark.subject: CharField -> ForeignKey(Subject), preserving data ---
        migrations.RenameField(model_name='mark', old_name='subject', new_name='subject_old'),
        migrations.AddField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marks.subject'),
        ),

        # Create lookup rows from the legacy strings and point every row at the right FK.
        # NOTE: the "drop old columns / tighten to non-null" steps live in the NEXT
        # migration (0005a) on purpose. Postgres refuses to ALTER TABLE a table that
        # had rows UPDATEd (via this RunPython) earlier in the *same* transaction
        # ("cannot ALTER TABLE ... because it has pending trigger events"). Splitting
        # across a migration boundary guarantees a real COMMIT happens in between.
        migrations.RunPython(backfill_fk_data, noop_reverse),
    ]
