# Generated by Django 5.2.15 on 2026-07-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005a_finalize_exam_category_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcategoryconfig',
            name='subjects',
        ),
        migrations.AddField(
            model_name='examcategory',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='marks.subject'),
        ),
    ]
