# Generated by Django 4.2.30 on 2026-07-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0006_remove_groupcategoryconfig_subjects_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examcategory',
            options={'verbose_name_plural': '2. Exam Categories'},
        ),
        migrations.AlterModelOptions(
            name='examtype',
            options={'verbose_name_plural': '4. Exam Types'},
        ),
        migrations.AlterModelOptions(
            name='groupcategoryconfig',
            options={'verbose_name_plural': '3. Connect Category to Group'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': '1. Subjects'},
        ),
    ]
