# Generated by Django 5.2.15 on 2026-08-15 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_blocked_at_user_blocked_reason_and_more'),
        ('marks', '0008_marksentrylock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksWhatsAppSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('student_count', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_send_logs', to='marks.exam')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_send_logs', to='accounts.section')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marks WhatsApp Send Log',
                'verbose_name_plural': '6. Marks WhatsApp Send Logs',
                'unique_together': {('exam', 'section')},
            },
        ),
    ]
