# Generated by Django 5.2.17 on 2026-08-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0009_markswhatsappsendlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='excluded_subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects excluded/not conducted for this specific exam instance.', related_name='excluded_from_exams', to='marks.subject'),
        ),
    ]
