# Generated by Django 5.2.15 on 2026-09-20 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0010_exam_excluded_subjects'),
        ('students', '0009_alter_student_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('source', models.CharField(choices=[('auto', 'Auto Calculated'), ('manual', 'Manually Entered')], default='auto', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_totals', to='marks.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_totals', to='students.student')),
            ],
            options={
                'verbose_name': 'Mark Total',
                'verbose_name_plural': 'Mark Totals',
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
