# Generated by Django 5.2.15 on 2026-08-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='08:00:00', help_text='Start time for attendance window (e.g. 08:00 AM)')),
                ('end_time', models.TimeField(default='09:00:00', help_text='End time for attendance window (e.g. 09:00 AM)')),
                ('is_active', models.BooleanField(default=True, help_text='Enable time window restrictions for faculty')),
            ],
            options={
                'verbose_name': 'Attendance Window Configuration',
                'verbose_name_plural': 'Attendance Window Configurations',
            },
        ),
    ]
